version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: brewerydash_backend/Dockerfile
    volumes:
      - ./brewerydash_backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend